### ISSUE TITLE
Add JavaScript/TypeScript

### ISSUE THREAD

**Issue by deadcoder0904** [max-lee-dev/hackertype#3]
Probably the most popular languages.

**Comment by max-lee-dev** [comment]
![image](https://github.com/max-lee-dev/hackertype/assets/109012823/8a822c5f-d662-4d6b-b6b5-4a8678f8938b)

added! enjoy :)

**Comment by deadcoder0904** [comment]
damn bro, thanks. that was quick. til about https://walkccc.me/LeetCode/problems/0001/

**Comment by max-lee-dev** [comment]
> damn bro, thanks. that was quick. til about https://walkccc.me/LeetCode/problems/0001/

sorry, what do you mean?

**Comment by deadcoder0904** [comment]
i didn't know the site (walkccc.me) existed before hence til (today i learned)
